### ISSUE TITLE
Version 0.3.3 marked as latest version on statamic

### ISSUE THREAD

**Issue by ghost** [doefom/statamic-export#3]
Hi! Just noticed that the package is still marked as 0.3.3 on Statamic: https://statamic.com/addons/doefom/export

Updating via the terminal works as expected and 0.4.0 also works as intended, however the CMS shows the package as out of date:

![statamic](https://github.com/user-attachments/assets/7ce4a427-b0f7-4587-9766-5a295cf1e54c)
![cms](https://github.com/user-attachments/assets/56919389-08b8-42dd-b9e7-24034d89ba0e)

Nice package btw :))

**Comment by doefom** [comment]
@matthiasbalota thanks for reaching out! I updated the minimum git version in the Statamic admin area. Did this fix the issue?

**Comment by ghost** [comment]
Yep, its fixed now. Thanks! :D
